# Generated by Django 4.1 on 2024-06-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0002_registereduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='report',
            field=models.TextField(blank=True),
        ),
    ]
