# Generated by Django 4.1 on 2024-06-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0003_registereduser_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='description',
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='picture',
            field=models.ImageField(default='', upload_to='parking_lot_pictures/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
