# Generated by Django 4.1 on 2024-07-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0004_remove_parkinglot_description_parkinglot_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='current_free_spot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='reviews',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='unit_of_time',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='vehicle_type',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
