# Generated by Django 4.1 on 2024-07-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0005_parkinglot_current_free_spot_parkinglot_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='current_free_spot',
            field=models.IntegerField(default=False),
        ),
    ]
