# Generated by Django 4.1 on 2024-07-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_app", "0006_alter_parkinglot_current_free_spot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkinglot",
            name="picture",
            field=models.ImageField(upload_to="./parking_lot_pictures/"),
        ),
    ]
